[package]
name = "wasm-glow-ballers-js"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-glow-ballers-lib = { path = "../wasm-glow-ballers-lib" }
wasm-bindgen = "0.2.100"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
